name: Print Environment Value  
on:  
  workflow_dispatch:  
    inputs:  
      environment:  
        type: choice  
        description: 'Which environment will be deployed?'  
        required: true  
        options:  
          - dev  
          - uat  
          - prod 
  
jobs:  
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "environment=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
  print:  
    runs-on: ubuntu-latest  
    needs: set-environment 
    environment: ${{ needs.set-environment.outputs.environment }}

    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  
      
      - name: Set Environment Variables  
        id: set_env_vars  
        run: echo "Environment selected= ${{ needs.set-environment.outputs.environment }}"  
  
      - name: Echo a Message  
        run: echo "This is a sample message from GitHub Actions"  
  
      - name: Print Environment Variable 
        run: echo "The value of MY_VARIABLE is ${{ vars.SINDIA_VARIABLE }}"  
        env:  
          MY_VARIABLE: ${{ vars.SINDIA_VARIABLE }}
